### ISSUE TITLE
incompatible with the latest version of pymoo

### ISSUE THREAD

**Issue by Ringzl** [anyoptimization/pysamoo#3]
The code is incompatible with the latest version of pymoo and cannot run. I sincerely hope you can update this project.

**Comment by blankjul** [comment]
I have just updated the version. Should be fixed now!

**Comment by jacktang** [comment]
@blankjul what's your updates? and how can I apply the updates?
pysamoo is compatible with 0.6 version pymoo?

**Comment by jacktang** [comment]
Well, I updated the python package from pypi, and looking forward the new version source code. Really appreciate your work!

**Comment by jacktang** [comment]
@blankjul it seems the updated package is incompatible with pymoo 0.6.0.1, any plan to support the latest pymoo?

**Comment by blankjul** [comment]
@jacktang in general, yes, the plan should be to keep always both versions compatible.
I will try to carve out some time soon to update or at least see how much work it would be.

**Comment by simonbance** [comment]
@blankjul Hi Julian. Is this issue closed, or is there still a compatibility issue with the latest version of pymoo?
Thanks for this great project!

**Comment by blankjul** [comment]
The versions are now compatible.

I finally found the time to release a new version here as well. Please check it out and let me know if you have issues running it.
